import type { Product, Order, Customer, DiscountCoupon, EcommerceStat } from './types'

export const mockStats: EcommerceStat[] = [
  {
    title: 'Total Pendapatan',
    value: 'Rp 148.500.000',
    change: '+14.2%',
    isPositive: true,
    description: 'dibanding bulan lalu',
  },
  {
    title: 'Total Pesanan',
    value: '1.420',
    change: '+8.1%',
    isPositive: true,
    description: 'dibanding bulan lalu',
  },
  {
    title: 'Produk Terjual',
    value: '3.890',
    change: '+22.5%',
    isPositive: true,
    description: 'dibanding bulan lalu',
  },
  {
    title: 'Stok Kritis',
    value: '4 Produk',
    change: '-2',
    isPositive: false,
    description: 'perlu persediaan baru',
  },
]

export const mockSalesChartData = [
  { month: 'Jan', revenue: 45000000, orders: 320 },
  { month: 'Feb', revenue: 52000000, orders: 380 },
  { month: 'Mar', revenue: 61000000, orders: 450 },
  { month: 'Apr', revenue: 58000000, orders: 410 },
  { month: 'Mei', revenue: 75000000, orders: 540 },
  { month: 'Jun', revenue: 89000000, orders: 670 },
  { month: 'Jul', revenue: 98000000, orders: 720 },
  { month: 'Agu', revenue: 148500000, orders: 1420 },
]

export const mockCategoryData = [
  { name: 'Pakaian & Fashion', value: 45, fill: '#3b82f6' },
  { name: 'Elektronik & Gadget', value: 25, fill: '#10b981' },
  { name: 'Kecantikan & Masker', value: 15, fill: '#f59e0b' },
  { name: 'Sepatu & Aksesoris', value: 15, fill: '#8b5cf6' },
]

export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    name: 'Kemeja Oversized Cotton Premium',
    sku: 'SHIRT-COT-001',
    category: 'Pakaian & Fashion',
    price: 249000,
    stock: 45,
    status: 'in_stock',
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=150&auto=format&fit=crop&q=60',
    salesCount: 312,
  },
  {
    id: 'prod-2',
    name: 'Earphone Wireless TWS Pro 2',
    sku: 'GADGET-TWS-002',
    category: 'Elektronik & Gadget',
    price: 599000,
    stock: 3,
    status: 'low_stock',
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=150&auto=format&fit=crop&q=60',
    salesCount: 540,
  },
  {
    id: 'prod-3',
    name: 'Sepatu Sneakers Running V2',
    sku: 'SHOES-RN-003',
    category: 'Sepatu & Aksesoris',
    price: 789000,
    stock: 18,
    status: 'in_stock',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=150&auto=format&fit=crop&q=60',
    salesCount: 189,
  },
  {
    id: 'prod-4',
    name: 'Serum Wajah Hydrating Niacinamide 10%',
    sku: 'BEAUTY-SRM-004',
    category: 'Kecantikan & Masker',
    price: 129000,
    stock: 0,
    status: 'out_of_stock',
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=150&auto=format&fit=crop&q=60',
    salesCount: 890,
  },
  {
    id: 'prod-5',
    name: 'Jaket Denim Vintage Casual',
    sku: 'JACKET-DNM-005',
    category: 'Pakaian & Fashion',
    price: 450000,
    stock: 22,
    status: 'in_stock',
    image: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=150&auto=format&fit=crop&q=60',
    salesCount: 145,
  },
  {
    id: 'prod-6',
    name: 'Smartwatch Fitness Tracker GPS',
    sku: 'GADGET-SMW-006',
    category: 'Elektronik & Gadget',
    price: 899000,
    stock: 2,
    status: 'low_stock',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=150&auto=format&fit=crop&q=60',
    salesCount: 260,
  },
]

export const mockOrders: Order[] = [
  {
    id: 'ord-101',
    orderNumber: 'ORD-2026-001',
    customerName: 'Budi Santoso',
    customerEmail: 'budi.santoso@gmail.com',
    date: '27 Agu 2026, 14:20',
    totalAmount: 848000,
    paymentStatus: 'paid',
    orderStatus: 'processing',
    shippingAddress: 'Jl. Sudirman No. 45, Jakarta Selatan',
    items: [
      { productId: 'prod-1', productName: 'Kemeja Oversized Cotton Premium', quantity: 1, unitPrice: 249000 },
      { productId: 'prod-2', productName: 'Earphone Wireless TWS Pro 2', quantity: 1, unitPrice: 599000 },
    ],
  },
  {
    id: 'ord-102',
    orderNumber: 'ORD-2026-002',
    customerName: 'Siti Rahma',
    customerEmail: 'siti.rahma@yahoo.com',
    date: '27 Agu 2026, 11:05',
    totalAmount: 129000,
    paymentStatus: 'paid',
    orderStatus: 'shipped',
    shippingAddress: 'Gg. Mawar No. 12, Bandung',
    items: [
      { productId: 'prod-4', productName: 'Serum Wajah Hydrating Niacinamide 10%', quantity: 1, unitPrice: 129000 },
    ],
  },
  {
    id: 'ord-103',
    orderNumber: 'ORD-2026-003',
    customerName: 'Ahmad Prasetyo',
    customerEmail: 'ahmad.p@gmail.com',
    date: '26 Agu 2026, 18:45',
    totalAmount: 789000,
    paymentStatus: 'pending',
    orderStatus: 'pending',
    shippingAddress: 'Jl. Diponegoro No. 88, Surabaya',
    items: [
      { productId: 'prod-3', productName: 'Sepatu Sneakers Running V2', quantity: 1, unitPrice: 789000 },
    ],
  },
  {
    id: 'ord-104',
    orderNumber: 'ORD-2026-004',
    customerName: 'Dewi Lestari',
    customerEmail: 'dewi.l@gmail.com',
    date: '25 Agu 2026, 09:30',
    totalAmount: 450000,
    paymentStatus: 'paid',
    orderStatus: 'delivered',
    shippingAddress: 'Jl. Malioboro No. 10, Yogyakarta',
    items: [
      { productId: 'prod-5', productName: 'Jaket Denim Vintage Casual', quantity: 1, unitPrice: 450000 },
    ],
  },
  {
    id: 'ord-105',
    orderNumber: 'ORD-2026-005',
    customerName: 'Rian Hidayat',
    customerEmail: 'rian.h@hotmail.com',
    date: '24 Agu 2026, 16:15',
    totalAmount: 899000,
    paymentStatus: 'failed',
    orderStatus: 'cancelled',
    shippingAddress: 'Jl. Gatot Subroto No. 3, Medan',
    items: [
      { productId: 'prod-6', productName: 'Smartwatch Fitness Tracker GPS', quantity: 1, unitPrice: 899000 },
    ],
  },
]

export const mockCustomers: Customer[] = [
  {
    id: 'cust-1',
    name: 'Budi Santoso',
    email: 'budi.santoso@gmail.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Budi',
    phone: '0812-3456-7890',
    totalOrders: 12,
    totalSpent: 4850000,
    joinedDate: '15 Jan 2025',
    status: 'active',
  },
  {
    id: 'cust-2',
    name: 'Siti Rahma',
    email: 'siti.rahma@yahoo.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Siti',
    phone: '0857-9876-5432',
    totalOrders: 8,
    totalSpent: 2390000,
    joinedDate: '02 Mar 2025',
    status: 'active',
  },
  {
    id: 'cust-3',
    name: 'Ahmad Prasetyo',
    email: 'ahmad.p@gmail.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ahmad',
    phone: '0819-1122-3344',
    totalOrders: 5,
    totalSpent: 1850000,
    joinedDate: '10 Mei 2025',
    status: 'active',
  },
  {
    id: 'cust-4',
    name: 'Dewi Lestari',
    email: 'dewi.l@gmail.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Dewi',
    phone: '0878-5566-7788',
    totalOrders: 2,
    totalSpent: 900000,
    joinedDate: '19 Jul 2025',
    status: 'inactive',
  },
]

export const mockDiscounts: DiscountCoupon[] = [
  {
    id: 'disc-1',
    code: 'MERDEKA2026',
    type: 'percentage',
    value: 17,
    minPurchase: 200000,
    usageLimit: 500,
    usedCount: 342,
    expiryDate: '31 Agu 2026',
    status: 'active',
  },
  {
    id: 'disc-2',
    code: 'GAJIAN50K',
    type: 'fixed',
    value: 50000,
    minPurchase: 300000,
    usageLimit: 200,
    usedCount: 200,
    expiryDate: '25 Agu 2026',
    status: 'expired',
  },
  {
    id: 'disc-3',
    code: 'NEWUSER10',
    type: 'percentage',
    value: 10,
    minPurchase: 100000,
    usageLimit: 1000,
    usedCount: 189,
    expiryDate: '31 Des 2026',
    status: 'active',
  },
]
